import type {
  BudgetItem,
  ClientRecord,
  Conversation,
  Guest,
  Lead,
  Message,
  TimelineTask,
  Vendor,
  WeddingDetails,
} from "@/types";

const images = {
  venue: "https://images.unsplash.com/photo-1519167758481-83f29c7c65c5?auto=format&fit=crop&w=1200&q=80",
  photo: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
  film: "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1200&q=80",
  floral: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1200&q=80",
  decor: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
  music: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
  catering: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=80",
  beauty: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
  cake: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&w=1200&q=80",
  planner: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
  transport: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
  invite: "https://images.unsplash.com/photo-1518133835878-5a93cc3f89e5?auto=format&fit=crop&w=1200&q=80",
};

export const weddingDetails: WeddingDetails = {
  couple: "Arjun & Maya",
  date: "2026-07-18",
  location: "Toronto, Ontario",
  style: "Modern luxury, elegant, South Asian fusion",
  budget: 35000,
  guestCount: 120,
};

export const vendors: Vendor[] = [
  {
    id: "golden-lens-photography",
    name: "Golden Lens Photography",
    category: "Photography",
    location: "Toronto, ON",
    rating: 4.9,
    reviewsCount: 148,
    startingPrice: 5200,
    image: images.photo,
    gallery: [images.photo, images.venue, images.floral],
    styleTags: ["Editorial", "Candid", "South Asian"],
    availability: "Available",
    matchScore: 96,
    responseTime: "2 hours",
    socials: ["Instagram", "Pinterest", "Website"],
    about:
      "A Toronto photography studio known for warm editorial storytelling, multi-day South Asian celebrations, and calm day-of direction.",
    packages: [
      {
        name: "Signature Story",
        price: 5200,
        description: "Full wedding day coverage with two photographers.",
        includes: ["10 hours coverage", "Two photographers", "Online gallery", "Engagement session"],
      },
      {
        name: "Weekend Collection",
        price: 7800,
        description: "Coverage for rehearsal, ceremony, reception, and family events.",
        includes: ["Two event days", "Highlight gallery", "Albums credit", "Timeline consult"],
      },
    ],
    reviews: [
      {
        id: "r1",
        author: "Priya & Daniel",
        rating: 5,
        date: "2025-09-14",
        body: "They captured every important family moment without making the day feel staged.",
      },
      {
        id: "r2",
        author: "Elena & Mark",
        rating: 5,
        date: "2025-06-21",
        body: "Elegant, organized, and fast with previews. The gallery felt like a magazine spread.",
      },
    ],
    pastWeddings: [
      {
        id: "pw1",
        couple: "Priya & Daniel",
        venue: "Graydon Hall Manor",
        style: "Garden reception",
        image: images.venue,
      },
      {
        id: "pw2",
        couple: "Nisha & Amar",
        venue: "The Symes",
        style: "Modern mandap",
        image: images.decor,
      },
    ],
    faqs: [
      { question: "Do you shoot multi-day weddings?", answer: "Yes, with custom weekend collections." },
      { question: "When are galleries delivered?", answer: "Preview gallery in one week and full gallery in eight weeks." },
    ],
  },
  {
    id: "ivory-bloom-florals",
    name: "Ivory Bloom Florals",
    category: "Florals",
    location: "Mississauga, ON",
    rating: 4.8,
    reviewsCount: 91,
    startingPrice: 3400,
    image: images.floral,
    gallery: [images.floral, images.decor],
    styleTags: ["Lush", "Neutral", "Romantic"],
    availability: "Limited",
    matchScore: 91,
    responseTime: "5 hours",
    socials: ["Instagram", "Website"],
    about: "Floral design studio creating layered ceremony arches, reception tablescapes, and personal flowers.",
    packages: [
      { name: "Ceremony Focus", price: 3400, description: "Personal flowers and ceremony florals.", includes: ["Bouquets", "Boutonnieres", "Aisle florals", "Arch accents"] },
      { name: "Full Floral Design", price: 6200, description: "Ceremony and reception floral direction.", includes: ["Centerpieces", "Candles", "Installations", "Strike team"] },
    ],
    reviews: [
      { id: "r3", author: "Mira & Josh", rating: 5, date: "2025-08-03", body: "The florals transformed a simple ballroom into something cinematic." },
    ],
    pastWeddings: [
      { id: "pw3", couple: "Mira & Josh", venue: "Four Seasons Toronto", style: "White orchid reception", image: images.floral },
    ],
    faqs: [{ question: "Can you reuse ceremony flowers?", answer: "Yes, the team often repurposes ceremony designs for reception focal areas." }],
  },
  {
    id: "maison-etoile-venue",
    name: "Maison Etoile Venue",
    category: "Venues",
    location: "Toronto, ON",
    rating: 4.9,
    reviewsCount: 207,
    startingPrice: 9500,
    image: images.venue,
    gallery: [images.venue, images.decor, images.catering],
    styleTags: ["Luxury", "Ballroom", "Downtown"],
    availability: "Available",
    matchScore: 94,
    responseTime: "1 day",
    socials: ["Instagram", "Website"],
    about: "A refined downtown venue with a grand ballroom, private terrace, and strong vendor operations team.",
    packages: [
      { name: "Saturday Prime", price: 9500, description: "Prime date rental with ceremony and reception access.", includes: ["Ballroom", "Terrace", "Suite", "Event captain"] },
      { name: "Full Venue Buyout", price: 14200, description: "Exclusive use of the property.", includes: ["All rooms", "Extended access", "Security", "Coat check"] },
    ],
    reviews: [
      { id: "r4", author: "Rina & Dev", rating: 5, date: "2025-07-19", body: "The operations team made a 180-person wedding feel easy." },
    ],
    pastWeddings: [
      { id: "pw4", couple: "Rina & Dev", venue: "Maison Etoile", style: "Black tie fusion", image: images.venue },
    ],
    faqs: [{ question: "Is outside catering allowed?", answer: "Preferred partners are recommended, with exceptions reviewed by the venue team." }],
  },
  {
    id: "velvet-hour-films",
    name: "Velvet Hour Films",
    category: "Videography",
    location: "Toronto, ON",
    rating: 4.8,
    reviewsCount: 76,
    startingPrice: 4700,
    image: images.film,
    gallery: [images.film, images.photo],
    styleTags: ["Cinematic", "Documentary", "Drone"],
    availability: "Available",
    matchScore: 89,
    responseTime: "3 hours",
    socials: ["Vimeo", "Instagram", "Website"],
    about: "Cinematic wedding films with natural audio, clean color, and short-form social edits.",
    packages: [
      { name: "Highlight Film", price: 4700, description: "Core wedding film package.", includes: ["8 hours coverage", "5 minute film", "Ceremony edit", "Speeches edit"] },
    ],
    reviews: [
      { id: "r5", author: "Sofia & Liam", rating: 5, date: "2025-05-11", body: "Their film felt emotional without feeling overly produced." },
    ],
    pastWeddings: [{ id: "pw5", couple: "Sofia & Liam", venue: "Evergreen Brick Works", style: "Modern industrial", image: images.film }],
    faqs: [{ question: "Do you include raw footage?", answer: "Raw footage can be added to any collection." }],
  },
  {
    id: "dj-nova-events",
    name: "DJ Nova Events",
    category: "DJ / Music",
    location: "Brampton, ON",
    rating: 4.7,
    reviewsCount: 122,
    startingPrice: 2600,
    image: images.music,
    gallery: [images.music, images.decor],
    styleTags: ["Bollywood", "Top 40", "Baraat"],
    availability: "Available",
    matchScore: 93,
    responseTime: "4 hours",
    socials: ["Instagram", "TikTok", "Website"],
    about: "High-energy DJ and MC team specializing in fusion receptions, baraat entrances, and packed dance floors.",
    packages: [
      { name: "Reception Party", price: 2600, description: "DJ and MC for ceremony and reception.", includes: ["Sound system", "Wireless mics", "Lighting", "Planning call"] },
    ],
    reviews: [{ id: "r6", author: "Anika & Sam", rating: 5, date: "2025-10-04", body: "The dance floor was full from the first song to the last." }],
    pastWeddings: [{ id: "pw6", couple: "Anika & Sam", venue: "Liberty Grand", style: "Bollywood reception", image: images.music }],
    faqs: [{ question: "Do you support ceremony audio?", answer: "Yes, ceremony and cocktail hour audio can be included." }],
  },
  {
    id: "saffron-sage-catering",
    name: "Saffron & Sage Catering",
    category: "Catering",
    location: "Scarborough, ON",
    rating: 4.8,
    reviewsCount: 184,
    startingPrice: 8200,
    image: images.catering,
    gallery: [images.catering, images.venue],
    styleTags: ["South Asian", "Family style", "Late night"],
    availability: "Limited",
    matchScore: 97,
    responseTime: "1 day",
    socials: ["Instagram", "Website"],
    about: "Full-service catering with South Asian menus, passed appetizers, plated service, and late-night stations.",
    packages: [
      { name: "Fusion Dinner", price: 8200, description: "Dinner service for 120 guests.", includes: ["Cocktail bites", "Dinner", "Staffing", "Late-night chai"] },
    ],
    reviews: [{ id: "r7", author: "Leena & Arjun", rating: 5, date: "2025-04-26", body: "Guests still talk about the food months later." }],
    pastWeddings: [{ id: "pw7", couple: "Leena & Arjun", venue: "The Guild Inn", style: "Family style dinner", image: images.catering }],
    faqs: [{ question: "Do you handle rentals?", answer: "Staffing, rentals, and serviceware can be bundled." }],
  },
  {
    id: "luxe-mandap-decor",
    name: "Luxe Mandap Decor",
    category: "Decor",
    location: "Vaughan, ON",
    rating: 4.9,
    reviewsCount: 113,
    startingPrice: 6800,
    image: images.decor,
    gallery: [images.decor, images.floral],
    styleTags: ["Mandap", "Draping", "Modern"],
    availability: "Available",
    matchScore: 95,
    responseTime: "6 hours",
    socials: ["Instagram", "Website"],
    about: "Mandap, stage, lighting, and reception decor with modern materials and precise installation teams.",
    packages: [
      { name: "Modern Mandap", price: 6800, description: "Ceremony mandap and aisle design.", includes: ["Mandap", "Draping", "Aisle", "Setup and strike"] },
    ],
    reviews: [{ id: "r8", author: "Nisha & Amar", rating: 5, date: "2025-06-08", body: "They made a large ballroom feel personal and refined." }],
    pastWeddings: [{ id: "pw8", couple: "Nisha & Amar", venue: "The Symes", style: "Sculptural mandap", image: images.decor }],
    faqs: [{ question: "Can decor be customized?", answer: "Yes, mood boards and custom renderings are included for full packages." }],
  },
  {
    id: "aura-bridal-beauty",
    name: "Aura Bridal Beauty",
    category: "Makeup",
    location: "Etobicoke, ON",
    rating: 4.7,
    reviewsCount: 88,
    startingPrice: 1300,
    image: images.beauty,
    gallery: [images.beauty, images.photo],
    styleTags: ["Soft glam", "Bridal", "Long wear"],
    availability: "Available",
    matchScore: 88,
    responseTime: "8 hours",
    socials: ["Instagram", "Website"],
    about: "Bridal makeup team specializing in long-wear glam for full wedding days and outdoor portraits.",
    packages: [
      { name: "Bride + Trial", price: 1300, description: "Bridal makeup with trial.", includes: ["Trial", "Wedding day makeup", "Lashes", "Touch-up kit"] },
    ],
    reviews: [{ id: "r9", author: "Jasmine & Theo", rating: 5, date: "2025-03-22", body: "The makeup lasted through tears, photos, and dancing." }],
    pastWeddings: [],
    faqs: [{ question: "Do you travel?", answer: "Travel is available across the GTA." }],
  },
  {
    id: "the-white-fig-cake-studio",
    name: "The White Fig Cake Studio",
    category: "Cake / Desserts",
    location: "Toronto, ON",
    rating: 4.8,
    reviewsCount: 63,
    startingPrice: 950,
    image: images.cake,
    gallery: [images.cake, images.floral],
    styleTags: ["Minimal", "Dessert table", "Custom"],
    availability: "Available",
    matchScore: 86,
    responseTime: "1 day",
    socials: ["Instagram", "Website"],
    about: "Modern wedding cakes, dessert tables, and South Asian sweet boxes with refined presentation.",
    packages: [
      { name: "Signature Cake", price: 950, description: "Three-tier custom wedding cake.", includes: ["Design consult", "Tasting box", "Delivery", "Setup"] },
    ],
    reviews: [{ id: "r10", author: "Hannah & Vik", rating: 5, date: "2025-02-15", body: "Beautiful design and the pistachio rose flavor was a standout." }],
    pastWeddings: [],
    faqs: [{ question: "Can we add a dessert table?", answer: "Yes, dessert tables can include mini cakes, tarts, and mithai boxes." }],
  },
  {
    id: "everafter-planning-co",
    name: "EverAfter Planning Co.",
    category: "Wedding Planner",
    location: "Toronto, ON",
    rating: 4.9,
    reviewsCount: 134,
    startingPrice: 4100,
    image: images.planner,
    gallery: [images.planner, images.venue],
    styleTags: ["Full planning", "Fusion", "Logistics"],
    availability: "Limited",
    matchScore: 92,
    responseTime: "3 hours",
    socials: ["Instagram", "Website"],
    about: "Planning and coordination team for complex family logistics, vendor management, and premium guest experiences.",
    packages: [
      { name: "Month-of Control", price: 4100, description: "Final logistics and day-of coordination.", includes: ["Timeline", "Vendor comms", "Rehearsal", "Wedding day team"] },
    ],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you manage vendor contracts?", answer: "Yes, contract tracking and vendor communication are included." }],
  },
  {
    id: "silk-route-invitations",
    name: "Silk Route Invitations",
    category: "Invitations",
    location: "Markham, ON",
    rating: 4.6,
    reviewsCount: 42,
    startingPrice: 780,
    image: images.invite,
    gallery: [images.invite, images.floral],
    styleTags: ["Letterpress", "Digital RSVP", "Custom"],
    availability: "Available",
    matchScore: 84,
    responseTime: "1 day",
    socials: ["Instagram", "Website"],
    about: "Invitation suites, save-the-dates, menus, signage, and digital RSVP pages.",
    packages: [{ name: "Printed Suite", price: 780, description: "Custom invitation suite for 120 guests.", includes: ["Design", "Printing", "Envelopes", "Proofs"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you support multiple languages?", answer: "Yes, bilingual suites are available." }],
  },
  {
    id: "cityline-chauffeurs",
    name: "CityLine Chauffeurs",
    category: "Transportation",
    location: "Toronto, ON",
    rating: 4.7,
    reviewsCount: 58,
    startingPrice: 1250,
    image: images.transport,
    gallery: [images.transport, images.venue],
    styleTags: ["Luxury car", "Shuttle", "Airport"],
    availability: "Available",
    matchScore: 80,
    responseTime: "2 hours",
    socials: ["Website"],
    about: "Wedding transportation with luxury sedans, guest shuttles, and coordinated pickup manifests.",
    packages: [{ name: "Wedding Shuttle", price: 1250, description: "Guest shuttle loop and couple car.", includes: ["Two shuttles", "Couple sedan", "Dispatch", "Pickup plan"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Can you handle hotel routes?", answer: "Yes, the dispatcher creates pickup windows and route sheets." }],
  },
  {
    id: "vows-by-elaine",
    name: "Vows by Elaine",
    category: "Officiant",
    location: "Toronto, ON",
    rating: 4.9,
    reviewsCount: 71,
    startingPrice: 650,
    image: images.planner,
    gallery: [images.planner],
    styleTags: ["Personal", "Ceremony", "Legal"],
    availability: "Available",
    matchScore: 82,
    responseTime: "4 hours",
    socials: ["Website"],
    about: "Licensed officiant creating warm, personal ceremonies for multicultural couples.",
    packages: [{ name: "Custom Ceremony", price: 650, description: "Personal ceremony script and legal filing.", includes: ["Planning call", "Script", "Rehearsal notes", "Filing"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you attend rehearsals?", answer: "Rehearsals can be added when needed." }],
  },
  {
    id: "north-hall-events",
    name: "North Hall Events",
    category: "Venues",
    location: "Vaughan, ON",
    rating: 4.6,
    reviewsCount: 126,
    startingPrice: 7200,
    image: images.venue,
    gallery: [images.venue],
    styleTags: ["Banquet", "Large guest count", "Parking"],
    availability: "Available",
    matchScore: 78,
    responseTime: "1 day",
    socials: ["Website"],
    about: "Large-format event hall built for cultural weddings, parking-heavy guest lists, and late receptions.",
    packages: [{ name: "Grand Hall", price: 7200, description: "Hall rental with tables, linens, and captain.", includes: ["Hall", "Tables", "Linens", "Venue captain"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "What is the capacity?", answer: "The Grand Hall hosts up to 350 seated guests." }],
  },
  {
    id: "petal-house-design",
    name: "Petal House Design",
    category: "Florals",
    location: "Oakville, ON",
    rating: 4.7,
    reviewsCount: 49,
    startingPrice: 2800,
    image: images.floral,
    gallery: [images.floral],
    styleTags: ["Garden", "Seasonal", "Colorful"],
    availability: "Waitlist",
    matchScore: 73,
    responseTime: "2 days",
    socials: ["Instagram"],
    about: "Seasonal floral team focused on garden-inspired arrangements and locally sourced stems.",
    packages: [{ name: "Seasonal Essentials", price: 2800, description: "Personal flowers and simple reception pieces.", includes: ["Bouquets", "Bud vases", "Boutonnieres", "Delivery"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you do large installs?", answer: "Large installs are available for full-service weddings." }],
  },
  {
    id: "fusion-feast-co",
    name: "Fusion Feast Co.",
    category: "Catering",
    location: "Toronto, ON",
    rating: 4.5,
    reviewsCount: 98,
    startingPrice: 7000,
    image: images.catering,
    gallery: [images.catering],
    styleTags: ["Fusion", "Stations", "Vegetarian"],
    availability: "Available",
    matchScore: 79,
    responseTime: "8 hours",
    socials: ["Instagram", "Website"],
    about: "Interactive station catering with strong vegetarian menus and flexible service models.",
    packages: [{ name: "Station Dinner", price: 7000, description: "Dinner stations for 120 guests.", includes: ["Four stations", "Staffing", "Tasting", "Late snack"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you offer tastings?", answer: "Tastings are included after shortlisting." }],
  },
  {
    id: "halo-hair-collective",
    name: "Halo Hair Collective",
    category: "Hair",
    location: "Toronto, ON",
    rating: 4.8,
    reviewsCount: 52,
    startingPrice: 1100,
    image: images.beauty,
    gallery: [images.beauty],
    styleTags: ["Bridal hair", "Updos", "Family glam"],
    availability: "Available",
    matchScore: 87,
    responseTime: "6 hours",
    socials: ["Instagram"],
    about: "Mobile bridal hair team for brides, family members, and wedding party styling.",
    packages: [{ name: "Bride + Party", price: 1100, description: "Bride hair plus three wedding party members.", includes: ["Trial", "Bride", "Three party members", "Touch-up pins"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Can you start early morning?", answer: "Early starts are available for cultural wedding timelines." }],
  },
  {
    id: "signal-room-djs",
    name: "Signal Room DJs",
    category: "DJ / Music",
    location: "Toronto, ON",
    rating: 4.6,
    reviewsCount: 67,
    startingPrice: 2100,
    image: images.music,
    gallery: [images.music],
    styleTags: ["House", "Top 40", "MC"],
    availability: "Available",
    matchScore: 76,
    responseTime: "3 hours",
    socials: ["Instagram", "Website"],
    about: "Modern DJ collective with clean setups, ceremony audio, and flexible MC support.",
    packages: [{ name: "Reception Core", price: 2100, description: "Reception DJ with lighting.", includes: ["DJ", "Lighting", "Mics", "Playlist consult"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Can we provide a do-not-play list?", answer: "Yes, playlists and do-not-play lists are part of planning." }],
  },
  {
    id: "copperline-films",
    name: "Copperline Films",
    category: "Videography",
    location: "Hamilton, ON",
    rating: 4.7,
    reviewsCount: 44,
    startingPrice: 3900,
    image: images.film,
    gallery: [images.film],
    styleTags: ["Documentary", "Super 8", "Social cuts"],
    availability: "Available",
    matchScore: 81,
    responseTime: "9 hours",
    socials: ["Vimeo", "Instagram"],
    about: "Documentary wedding films with optional Super 8 texture and vertical social trailers.",
    packages: [{ name: "Documentary Film", price: 3900, description: "Wedding day film coverage.", includes: ["8 hours", "Highlight film", "Audio capture", "Social trailer"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you work with photographers?", answer: "Yes, the team coordinates with photo vendors before the wedding day." }],
  },
  {
    id: "paper-lantern-studio",
    name: "Paper Lantern Studio",
    category: "Invitations",
    location: "Toronto, ON",
    rating: 4.7,
    reviewsCount: 39,
    startingPrice: 620,
    image: images.invite,
    gallery: [images.invite],
    styleTags: ["Minimal", "Menus", "Seating charts"],
    availability: "Available",
    matchScore: 75,
    responseTime: "1 day",
    socials: ["Instagram", "Website"],
    about: "Day-of stationery, invitation suites, and seating displays with modern typography.",
    packages: [{ name: "Day-of Paper", price: 620, description: "Menus, programs, and table numbers.", includes: ["Menus", "Programs", "Table numbers", "Print proofs"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Do you create seating charts?", answer: "Yes, large-format seating charts are available." }],
  },
  {
    id: "honey-fig-desserts",
    name: "Honey Fig Desserts",
    category: "Cake / Desserts",
    location: "Mississauga, ON",
    rating: 4.6,
    reviewsCount: 51,
    startingPrice: 850,
    image: images.cake,
    gallery: [images.cake],
    styleTags: ["Dessert table", "Macarons", "Mithai"],
    availability: "Limited",
    matchScore: 83,
    responseTime: "1 day",
    socials: ["Instagram"],
    about: "Dessert tables blending French pastries, mithai, and modern wedding cake design.",
    packages: [{ name: "Dessert Table", price: 850, description: "Assorted desserts for 120 guests.", includes: ["Cake", "Mini pastries", "Mithai", "Display rentals"] }],
    reviews: [],
    pastWeddings: [],
    faqs: [{ question: "Can desserts be boxed as favors?", answer: "Yes, favor packaging can be added." }],
  },
];

export const budgetItems: BudgetItem[] = [
  { id: "b1", category: "Venue", label: "Maison Etoile venue deposit", vendorId: "maison-etoile-venue", amount: 8000, paid: 5000, dueDate: "2026-06-01", status: "Deposit Paid" },
  { id: "b2", category: "Catering", label: "Saffron & Sage dinner service", vendorId: "saffron-sage-catering", amount: 7200, paid: 3500, dueDate: "2026-06-15", status: "Deposit Paid" },
  { id: "b3", category: "Decor", label: "Luxe Mandap ceremony decor", vendorId: "luxe-mandap-decor", amount: 4800, paid: 2500, dueDate: "2026-06-20", status: "Deposit Paid" },
  { id: "b4", category: "Invitations", label: "Printed invitation suite", amount: 800, paid: 800, dueDate: "2026-04-10", status: "Paid" },
  { id: "b5", category: "Attire", label: "Reception outfits", amount: 200, paid: 200, dueDate: "2026-05-20", status: "Paid" },
  { id: "b6", category: "Music", label: "DJ placeholder estimate", amount: 2500, paid: 0, dueDate: "2026-06-25", status: "Planned" },
  { id: "b7", category: "Florals", label: "Floral estimate", amount: 3200, paid: 0, dueDate: "2026-06-18", status: "Planned" },
  { id: "b8", category: "Makeup", label: "Bridal makeup estimate", amount: 1300, paid: 0, dueDate: "2026-07-01", status: "Planned" },
  { id: "b9", category: "Transportation", label: "Guest shuttle estimate", amount: 1200, paid: 0, dueDate: "2026-07-05", status: "Planned" },
  { id: "b10", category: "Cake", label: "Cake and dessert estimate", amount: 1000, paid: 0, dueDate: "2026-06-30", status: "Planned" },
];

const guestGroups = ["Patel family", "Sharma family", "University friends", "Work friends", "Cousins", "Family friends"];
const mealChoices: Guest["mealChoice"][] = ["Chicken", "Vegetarian", "Vegan", "Halal", "Pending"];
const statuses: Guest["status"][] = ["Attending", "Attending", "Attending", "Pending", "Pending", "Declined"];

export const guests: Guest[] = Array.from({ length: 50 }, (_, index) => ({
  id: `g${index + 1}`,
  name:
    [
      "Aarav Patel",
      "Isha Mehta",
      "Rohan Singh",
      "Neha Kapoor",
      "Sameer Khan",
      "Amara Shah",
      "Lucas Chen",
      "Mina Desai",
      "Daniel Reed",
      "Sonia Gill",
    ][index % 10] + ` ${index + 1}`,
  email: `guest${index + 1}@example.com`,
  phone: `416-555-${String(1000 + index).slice(0, 4)}`,
  group: guestGroups[index % guestGroups.length],
  status: statuses[index % statuses.length],
  plusOne: index % 4 === 0,
  mealChoice: mealChoices[index % mealChoices.length],
  tableNumber: index % 6 === 0 ? undefined : (index % 12) + 1,
  notes: index % 9 === 0 ? "Needs shuttle from hotel." : undefined,
}));

export const timelineTasks: TimelineTask[] = [
  { id: "t1", title: "Book venue", group: "12 months before", dueDate: "2025-08-01", completed: true, relatedVendorId: "maison-etoile-venue", priority: "High" },
  { id: "t2", title: "Hire photographer", group: "12 months before", dueDate: "2025-09-01", completed: false, relatedVendorId: "golden-lens-photography", priority: "High" },
  { id: "t3", title: "Choose catering direction", group: "9 months before", dueDate: "2025-10-15", completed: true, relatedVendorId: "saffron-sage-catering", priority: "High" },
  { id: "t4", title: "Finalize guest list", group: "9 months before", dueDate: "2025-11-01", completed: false, priority: "High" },
  { id: "t5", title: "Book decor team", group: "9 months before", dueDate: "2025-11-15", completed: true, relatedVendorId: "luxe-mandap-decor", priority: "High" },
  { id: "t6", title: "Select videographer", group: "6 months before", dueDate: "2026-01-15", completed: false, relatedVendorId: "velvet-hour-films", priority: "Medium" },
  { id: "t7", title: "Send invitations", group: "6 months before", dueDate: "2026-02-01", completed: true, relatedVendorId: "silk-route-invitations", priority: "Medium" },
  { id: "t8", title: "Book DJ and MC", group: "6 months before", dueDate: "2026-02-15", completed: false, relatedVendorId: "dj-nova-events", priority: "High" },
  { id: "t9", title: "Schedule engagement shoot", group: "6 months before", dueDate: "2026-02-28", completed: false, relatedVendorId: "golden-lens-photography", priority: "Medium" },
  { id: "t10", title: "Confirm catering menu", group: "3 months before", dueDate: "2026-04-20", completed: false, relatedVendorId: "saffron-sage-catering", priority: "High" },
  { id: "t11", title: "Plan seating chart", group: "3 months before", dueDate: "2026-05-01", completed: false, priority: "Medium" },
  { id: "t12", title: "Book bridal makeup", group: "3 months before", dueDate: "2026-05-15", completed: false, relatedVendorId: "aura-bridal-beauty", priority: "Medium" },
  { id: "t13", title: "Book hair team", group: "3 months before", dueDate: "2026-05-20", completed: false, relatedVendorId: "halo-hair-collective", priority: "Medium" },
  { id: "t14", title: "Order cake", group: "3 months before", dueDate: "2026-05-25", completed: false, relatedVendorId: "the-white-fig-cake-studio", priority: "Low" },
  { id: "t15", title: "Finalize transportation", group: "1 month before", dueDate: "2026-06-15", completed: false, relatedVendorId: "cityline-chauffeurs", priority: "Medium" },
  { id: "t16", title: "Final dress fitting", group: "1 month before", dueDate: "2026-06-18", completed: false, priority: "High" },
  { id: "t17", title: "Confirm vendor arrival times", group: "Wedding week", dueDate: "2026-07-12", completed: false, priority: "High" },
  { id: "t18", title: "Create day-of schedule", group: "Wedding week", dueDate: "2026-07-13", completed: false, priority: "High" },
  { id: "t19", title: "Pack getting-ready details", group: "Wedding week", dueDate: "2026-07-15", completed: false, priority: "Medium" },
  { id: "t20", title: "Share final floor plan", group: "Wedding day", dueDate: "2026-07-18", completed: false, priority: "High" },
];

export const leads: Lead[] = [
  { id: "l1", vendorId: "golden-lens-photography", coupleNames: "Mina & Jacob", weddingDate: "2026-08-22", budget: 42000, location: "Toronto, ON", guestCount: 140, serviceRequested: "Photography", lastMessage: "Can you send availability for August?", stage: "Contacted", estimatedValue: 5800, createdAt: "2026-04-21T10:00:00Z" },
  { id: "l2", vendorId: "golden-lens-photography", coupleNames: "Sana & Miles", weddingDate: "2026-09-05", budget: 38000, location: "Vaughan, ON", guestCount: 110, serviceRequested: "Photography", lastMessage: "We love your editorial galleries.", stage: "Proposal Sent", estimatedValue: 5200, createdAt: "2026-04-24T14:00:00Z" },
  { id: "l3", vendorId: "golden-lens-photography", coupleNames: "Rachel & Dev", weddingDate: "2026-10-10", budget: 50000, location: "Niagara-on-the-Lake, ON", guestCount: 160, serviceRequested: "Photography", lastMessage: "Can we add rehearsal dinner coverage?", stage: "Negotiating", estimatedValue: 7600, createdAt: "2026-04-25T15:30:00Z" },
  { id: "l4", vendorId: "golden-lens-photography", coupleNames: "Bianca & Omar", weddingDate: "2026-06-27", budget: 30000, location: "Toronto, ON", guestCount: 90, serviceRequested: "Photography", lastMessage: "Contract is signed, deposit paid.", stage: "Booked", estimatedValue: 4900, createdAt: "2026-03-12T09:00:00Z" },
  { id: "l5", vendorId: "golden-lens-photography", coupleNames: "Tara & Neil", weddingDate: "2026-11-14", budget: 36000, location: "Mississauga, ON", guestCount: 125, serviceRequested: "Photography", lastMessage: "Following up after the consultation.", stage: "New Inquiry", estimatedValue: 5200, createdAt: "2026-05-01T12:00:00Z" },
  { id: "l6", vendorId: "golden-lens-photography", coupleNames: "Evelyn & Marcus", weddingDate: "2026-12-05", budget: 47000, location: "Toronto, ON", guestCount: 150, serviceRequested: "Photography", lastMessage: "We are reviewing two collections.", stage: "Proposal Sent", estimatedValue: 6100, createdAt: "2026-04-28T17:00:00Z" },
  { id: "l7", vendorId: "golden-lens-photography", coupleNames: "Nadia & Julien", weddingDate: "2027-01-16", budget: 32000, location: "Hamilton, ON", guestCount: 100, serviceRequested: "Photography", lastMessage: "Date moved to 2027.", stage: "Lost", estimatedValue: 0, createdAt: "2026-03-22T11:00:00Z" },
];

export const conversations: Conversation[] = [
  { id: "c1", vendorId: "saffron-sage-catering", vendorName: "Saffron & Sage Catering", coupleName: "Arjun & Maya", unreadForCouple: 1, unreadForVendor: 0 },
  { id: "c2", vendorId: "luxe-mandap-decor", vendorName: "Luxe Mandap Decor", coupleName: "Arjun & Maya", unreadForCouple: 0, unreadForVendor: 0 },
  { id: "c3", vendorId: "maison-etoile-venue", vendorName: "Maison Etoile Venue", coupleName: "Arjun & Maya", unreadForCouple: 0, unreadForVendor: 0 },
];

export const messages: Message[] = [
  { id: "m1", conversationId: "c1", sender: "couple", senderName: "Maya", body: "Hi, can we confirm that the tasting menu includes vegetarian options?", timestamp: "2026-05-01T13:10:00Z" },
  { id: "m2", conversationId: "c1", sender: "vendor", senderName: "Saffron & Sage Catering", body: "Yes. We can do paneer tikka, chana masala, and a vegan biryani station.", timestamp: "2026-05-01T14:05:00Z" },
  { id: "m3", conversationId: "c1", sender: "couple", senderName: "Arjun", body: "Great. Please send the updated menu with late-night chai.", timestamp: "2026-05-02T10:22:00Z" },
  { id: "m4", conversationId: "c1", sender: "vendor", senderName: "Saffron & Sage Catering", body: "Updated menu is ready. I also added a jalebi station as an optional upgrade.", timestamp: "2026-05-02T11:10:00Z" },
  { id: "m5", conversationId: "c2", sender: "vendor", senderName: "Luxe Mandap Decor", body: "We uploaded the revised mandap mood board with champagne draping.", timestamp: "2026-04-30T16:15:00Z" },
  { id: "m6", conversationId: "c2", sender: "couple", senderName: "Maya", body: "The champagne draping works. Can we keep the aisle florals minimal?", timestamp: "2026-04-30T18:35:00Z" },
  { id: "m7", conversationId: "c2", sender: "vendor", senderName: "Luxe Mandap Decor", body: "Absolutely. We will shift more florals to the stage backdrop.", timestamp: "2026-05-01T09:12:00Z" },
  { id: "m8", conversationId: "c3", sender: "vendor", senderName: "Maison Etoile Venue", body: "Your final venue walkthrough is available on June 8 or June 10.", timestamp: "2026-05-02T08:25:00Z" },
  { id: "m9", conversationId: "c3", sender: "couple", senderName: "Arjun", body: "June 10 works best for us.", timestamp: "2026-05-02T09:40:00Z" },
  { id: "m10", conversationId: "c3", sender: "vendor", senderName: "Maison Etoile Venue", body: "Booked for June 10 at 5:30 PM. I will send the calendar hold.", timestamp: "2026-05-02T10:01:00Z" },
];

export const clientRecords: ClientRecord[] = [
  { id: "cr1", coupleNames: "Arjun & Maya", weddingDate: "2026-07-18", packageName: "Pending photography package", paymentStatus: "Invoice Due", contractStatus: "Draft", notes: "Interested in full wedding day plus engagement shoot." },
  { id: "cr2", coupleNames: "Bianca & Omar", weddingDate: "2026-06-27", packageName: "Signature Story", paymentStatus: "Deposit Paid", contractStatus: "Signed", notes: "Engagement gallery delivered." },
  { id: "cr3", coupleNames: "Mina & Jacob", weddingDate: "2026-08-22", packageName: "Weekend Collection", paymentStatus: "Invoice Due", contractStatus: "Pending", notes: "Awaiting final decision on rehearsal dinner." },
  { id: "cr4", coupleNames: "Sana & Miles", weddingDate: "2026-09-05", packageName: "Signature Story", paymentStatus: "Invoice Due", contractStatus: "Draft", notes: "Proposal sent April 24." },
  { id: "cr5", coupleNames: "Rachel & Dev", weddingDate: "2026-10-10", packageName: "Weekend Collection", paymentStatus: "Deposit Paid", contractStatus: "Pending", notes: "Negotiating album credit." },
];
